Updated handout code for 2025.

diff --git a/run-docker b/run-docker
--- a/run-docker
+++ b/run-docker
@@ -8,6 +8,7 @@ verbose=false
 arch="`arch`"
 tag=
 platform=
+container=
 while test "$#" -ne 0; do
     if test "$1" = "-f" -o "$1" = "--fresh"; then
         fresh=1
@@ -29,12 +30,15 @@ while test "$#" -ne 0; do
     elif test "(" "$1" = "-t" -o "$1" = "--tag" ")" -a "$#" -gt 1; then
         tag="$2"
         shift 2
+    elif test -z "$container" -a -z "$fresh" -a -n "$1" && expr "$1" : '[0-9a-f][0-9a-f][0-9a-f]*$' >/dev/null 2>&1; then
+        container="$1"
+        shift
     else
         armtext=
         if test "$arch" = "arm64" -o "$arch" = "aarch64"; then
             armtext=" [-a|--arm] [-x|--x86-64]"
         fi
-        echo "Usage: run-docker [-f|--fresh] [-t|--tag TAG]$armtext [-V|--verbose]" 1>&2
+        echo "Usage: run-docker [-f|--fresh]$armtext [-V|--verbose] [CONTAINERID]" 1>&2
         exit 1
     fi
 done
@@ -64,6 +68,13 @@ else
 fi
 myfileid=`stat $statformatarg %d:%i "${BASH_SOURCE[0]}" 2>/dev/null`
 
+ssharg=
+sshenvarg=
+if test -n "$SSH_AUTH_SOCK" -a "`uname`" = Darwin; then
+    ssharg=" --mount type=bind,src=/run/host-services/ssh-auth.sock,target=/run/host-services/ssh-auth.sock"
+    sshenvarg=" -e SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock"
+fi
+
 dir="`pwd`"
 subdir=""
 while test "$dir" != / -a "$dir" != ""; do
@@ -81,24 +92,31 @@ if test -z "$maindir" && expr "${BASH_SOURCE[0]}" : / >/dev/null 2>&1; then
     subdir=""
 fi
 
-ssharg=
-sshenvarg=
-if test -n "$SSH_AUTH_SOCK" -a "`uname`" = Darwin; then
-    ssharg=" --mount type=bind,src=/run/host-services/ssh-auth.sock,target=/run/host-services/ssh-auth.sock"
-    sshenvarg=" -e SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock"
-fi
-
-if test -n "$maindir" -a -z "$fresh"; then
-    existing_image="`docker ps -f status=running -f ancestor=$tag -f volume=/host_mnt"$maindir" --no-trunc --format "{{.CreatedAt}},{{.ID}}" | sort -r | head -n 1`"
-    if test -n "$existing_image"; then
-        created_at="`echo $existing_image | sed 's/,.*//'`"
-        image="`echo $existing_image | sed 's/^.*,//'`"
-        image12="`echo $image | head -c 12`"
-        echo "* Using running container $image12, created $created_at" 1>&2
-        echo "- To start a new container, exit then \`./run-docker -f\`" 1>&2
-        echo "- To kill this container, exit then \`docker kill $image12\`" 1>&2
-        vexec docker exec -it$sshenvarg $image /bin/bash
+existing_image=""
+if test -n "$container"; then
+    existing_image="`docker ps -f "id=$container" --no-trunc --format "{{.CreatedAt}},{{.ID}}" | sort -r | head -n 1`"
+    if test -z "$existing_image"; then
+        echo "* Container $container not found" 1>&2
+        echo "- To start a new container, try \`cs61-run-docker -f\`" 1>&2
+        echo "- To list executing containers, try \`docker ps\`" 1>&2
+        exit 1
+    elif test "`echo "$existing_image" | wc -l`" -gt 1; then
+        echo "* Container $container ambiguous" 1>&2
+        echo "- To start a new container, try \`cs61-run-docker -f\`" 1>&2
+        echo "- To list executing containers, try \`docker ps\`" 1>&2
+        exit 1
     fi
+elif test -n "$maindir" -a -z "$fresh"; then
+    existing_image="`docker ps -f status=running -f ancestor=$tag -f volume=/host_mnt"$maindir" --no-trunc --format "{{.CreatedAt}},{{.ID}}" | sort -r | head -n 1`"
+fi
+if test -n "$existing_image"; then
+    created_at="`echo $existing_image | sed 's/,.*//'`"
+    image="`echo $existing_image | sed 's/^.*,//'`"
+    image12="`echo $image | head -c 12`"
+    echo "* Using running container $image12, created $created_at" 1>&2
+    echo "- To start a new container, exit then \`run-docker -f\`" 1>&2
+    echo "- To kill this container, exit then \`docker kill $image12\`" 1>&2
+    vexec docker exec -it$sshenvarg $image /bin/bash
 fi
 
 netarg=
